application: notepyd
version: 4
runtime: python
api_version: 1

handlers:
- url: /scripts
  static_dir: scripts

- url: /styles
  static_dir: styles

- url: /images
  static_dir: images

- url: /MobWrite/static
  secure: optional
  static_dir: MobWrite/static
- url: /MobWrite/scripts/q.py
  secure: optional
  script: MobWrite/mobwrite_appengine.py
- url: /MobWrite/.*
  secure: optional
  script: MobWrite/mobwrite_appengine.py

- url: /.*
  script: main.py

error_handlers:
  - file: error.html

  - error_code: over_quota
    file: error.html